CREATE TABLE IF NOT EXISTS videos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    topic TEXT NOT NULL,
    account_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending_Script',
    script TEXT,
    script_sources TEXT,
    visual_keywords TEXT,
    voiceover_path TEXT,
    video_path TEXT,
    caption TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    qa_feedback TEXT,
    hook_score REAL,
    retention_estimate REAL,
    cta_text TEXT,
    is_sponsored INTEGER DEFAULT 0,
    compliance_metadata TEXT,
    post_snapchat INTEGER DEFAULT 0,
    post_x INTEGER DEFAULT 0,
    affiliate_url TEXT,
    error_message TEXT,
    auto_approve INTEGER DEFAULT 0,
    use_human_intro INTEGER DEFAULT 0,
    post_yt INTEGER DEFAULT 1,
    post_ig INTEGER DEFAULT 1,
    post_tt INTEGER DEFAULT 1,
    save_to_desktop INTEGER DEFAULT 1,
    script_retry_count INTEGER DEFAULT 0,
    api_cost_estimate REAL DEFAULT 0
);