CREATE TABLE IF NOT EXISTS videos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    topic TEXT NOT NULL,
    account_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending_Script',
    script TEXT,
    script_sources TEXT,
    visual_keywords TEXT,
    voiceover_path TEXT,
    video_path TEXT,
    caption TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    qa_feedback TEXT,
    hook_score REAL,
    retention_estimate REAL,
    cta_text TEXT,
    is_sponsored INTEGER DEFAULT 0,
    compliance_metadata TEXT,
    affiliate_url TEXT,
    error_message TEXT,
    auto_approve INTEGER DEFAULT 0,
    use_human_intro INTEGER DEFAULT 0,
    post_yt INTEGER DEFAULT 1,
    post_ig INTEGER DEFAULT 1,
    post_tt INTEGER DEFAULT 1,
    save_to_desktop INTEGER DEFAULT 1,
    script_retry_count INTEGER DEFAULT 0,
    api_cost_estimate REAL DEFAULT 0,
    final_path TEXT,
    voice_name TEXT,
    research_dossier TEXT,
    storyboard_draft TEXT,
    script_cost_estimate REAL DEFAULT 0,
    visual_qa_result TEXT,
    citation_qa_result TEXT
);

CREATE TABLE IF NOT EXISTS cost_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id INTEGER NOT NULL,
    stage TEXT NOT NULL,
    provider TEXT,
    model TEXT,
    tokens_in INTEGER DEFAULT 0,
    tokens_out INTEGER DEFAULT 0,
    usd REAL NOT NULL,
    note TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS pipeline_errors (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    video_id INTEGER NOT NULL,
    node TEXT NOT NULL,
    error_code TEXT NOT NULL,
    fingerprint TEXT NOT NULL,
    message TEXT NOT NULL,
    details_json TEXT,
    attempt INTEGER DEFAULT 1,
    cost_snapshot REAL DEFAULT 0,
    occurrence_count INTEGER DEFAULT 1,
    status TEXT DEFAULT 'open',
    auto_recovered INTEGER DEFAULT 0,
    first_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_seen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP,
    FOREIGN KEY(video_id) REFERENCES videos(id) ON DELETE CASCADE
);
